CREATE TABLE IF NOT EXISTS payment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date       date,
    amount     DOUBLE PRECISION                        NOT NULL,
    type       SMALLINT,
    status     SMALLINT,
    file       VARCHAR(255),
    student_id VARCHAR(255),
    CONSTRAINT pk_payment PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS student
(
    id         VARCHAR(255) NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    code       VARCHAR(255),
    programid  VARCHAR(255),
    photo      VARCHAR(255),
    CONSTRAINT pk_student PRIMARY KEY (id)
);

ALTER TABLE student
    ADD CONSTRAINT uc_student_code UNIQUE (code);

ALTER TABLE payment
    ADD CONSTRAINT FK_PAYMENT_ON_STUDENT FOREIGN KEY (student_id) REFERENCES student (id);